# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='English_Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=300)),
                ('director_name', models.CharField(max_length=50)),
                ('Hero_name', models.CharField(max_length=50)),
                ('Heroiene_name', models.CharField(max_length=50)),
                ('producer_name', models.CharField(max_length=50)),
                ('released_date', models.DateField(max_length=50)),
            ],
        ),
    ]
